#!/usr/bin/env bash
# Shared helpers for the Superset lifecycle scripts. Sourced, never executed.

if [ -t 1 ]; then
  _C_DIM=$'\033[2m'; _C_BLUE=$'\033[1;34m'; _C_GREEN=$'\033[1;32m'
  _C_YELLOW=$'\033[1;33m'; _C_RED=$'\033[1;31m'; _C_OFF=$'\033[0m'
else
  _C_DIM=''; _C_BLUE=''; _C_GREEN=''; _C_YELLOW=''; _C_RED=''; _C_OFF=''
fi

log()  { printf '%s>>%s %s\n' "$_C_BLUE"   "$_C_OFF" "$*"; }
ok()   { printf '%s ok%s %s\n' "$_C_GREEN" "$_C_OFF" "$*"; }
skip() { printf '%s  -%s %s\n' "$_C_DIM"   "$_C_OFF" "$*"; }
warn() { printf '%s  !%s %s\n' "$_C_YELLOW" "$_C_OFF" "$*" >&2; }
die()  { printf '%s  x%s %s\n' "$_C_RED"   "$_C_OFF" "$*" >&2; exit 1; }

have() { command -v "$1" >/dev/null 2>&1; }

# Superset sets SUPERSET_WORKSPACE_PATH, SUPERSET_WORKSPACE_NAME and
# SUPERSET_ROOT_PATH. Derive each from git when absent so these scripts stay
# runnable by hand, outside Superset.
resolve_superset_env() {
  if [ -z "${SUPERSET_WORKSPACE_PATH:-}" ]; then
    SUPERSET_WORKSPACE_PATH="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
  fi
  if [ -z "${SUPERSET_WORKSPACE_NAME:-}" ]; then
    SUPERSET_WORKSPACE_NAME="$(basename "$SUPERSET_WORKSPACE_PATH")"
  fi
  if [ -z "${SUPERSET_ROOT_PATH:-}" ]; then
    local common_dir
    common_dir="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null || true)"
    SUPERSET_ROOT_PATH="${common_dir:+$(dirname "$common_dir")}"
    SUPERSET_ROOT_PATH="${SUPERSET_ROOT_PATH:-$SUPERSET_WORKSPACE_PATH}"
  fi
  export SUPERSET_WORKSPACE_PATH SUPERSET_WORKSPACE_NAME SUPERSET_ROOT_PATH

  SUPERSET_DIR="$SUPERSET_WORKSPACE_PATH/.superset"
  PORTS_ENV_FILE="$SUPERSET_DIR/.ports.env"
  PORTS_LABEL_FILE="$SUPERSET_DIR/ports.json"
  PORT_ALLOCATOR="$SUPERSET_DIR/lib/ports.py"
  export SUPERSET_DIR PORTS_ENV_FILE PORTS_LABEL_FILE PORT_ALLOCATOR
}

# True when this workspace is the root checkout itself, not a worktree.
is_root_checkout() {
  [ "$(cd "$SUPERSET_WORKSPACE_PATH" && pwd -P)" = "$(cd "$SUPERSET_ROOT_PATH" 2>/dev/null && pwd -P)" ]
}

python_bin() { have python3 && echo python3 || echo python; }

# ---- Node package manager: the lockfile is what the repo actually commits,
# and installing with the wrong tool rewrites it. ----

detect_node_pm() {
  if   [ -f bun.lockb ] || [ -f bun.lock ]; then echo bun
  elif [ -f pnpm-lock.yaml ];               then echo pnpm
  elif [ -f yarn.lock ];                    then echo yarn
  elif [ -f package-lock.json ];            then echo npm
  elif [ -f package.json ];                 then echo npm
  else echo ""
  fi
}

node_install_cmd() {
  case "$1" in
    bun)  if [ -f bun.lockb ] || [ -f bun.lock ]; then echo "bun install --frozen-lockfile"; else echo "bun install"; fi ;;
    pnpm) echo "pnpm install --frozen-lockfile" ;;
    yarn) echo "yarn install --immutable" ;;
    npm)  if [ -f package-lock.json ]; then echo "npm ci"; else echo "npm install"; fi ;;
    *)    echo "" ;;
  esac
}

node_dev_cmd() {
  case "$1" in
    bun)  echo "bun run dev" ;;
    pnpm) echo "pnpm dev" ;;
    yarn) echo "yarn dev" ;;
    npm)  echo "npm run dev" ;;
    *)    echo "" ;;
  esac
}

# ---- Port block: 3 ports per workspace (web, api, sim) written to
# $PORTS_ENV_FILE so setup and run agree on the same numbers. ----

reserve_ports() {
  local base
  base="$("$(python_bin)" "$PORT_ALLOCATOR" reserve "$SUPERSET_WORKSPACE_PATH" \
    --name "$SUPERSET_WORKSPACE_NAME" --size 3 --start 3000)" || die "port reservation failed"

  WEB_PORT=$((base))
  API_PORT=$((base + 1))
  SIM_PORT=$((base + 2))

  cat > "$PORTS_ENV_FILE" <<EOF
# generated by .superset/setup.sh — do not edit by hand
WEB_PORT=$WEB_PORT
API_PORT=$API_PORT
SIM_PORT=$SIM_PORT
EOF

  cat > "$PORTS_LABEL_FILE" <<EOF
{
  "ports": [
    { "port": $WEB_PORT, "label": "Web (Vite) — $SUPERSET_WORKSPACE_NAME" },
    { "port": $API_PORT, "label": "API (FastAPI) — $SUPERSET_WORKSPACE_NAME" },
    { "port": $SIM_PORT, "label": "Sim WS server — $SUPERSET_WORKSPACE_NAME" }
  ]
}
EOF

  export WEB_PORT API_PORT SIM_PORT
}

load_ports() {
  if [ -f "$PORTS_ENV_FILE" ]; then
    # shellcheck source=/dev/null
    source "$PORTS_ENV_FILE"
  else
    reserve_ports
  fi
}

release_ports() {
  "$(python_bin)" "$PORT_ALLOCATOR" release "$SUPERSET_WORKSPACE_PATH" 2>/dev/null || true
  rm -f "$PORTS_ENV_FILE" "$PORTS_LABEL_FILE"
}
